### ISSUE TITLE
[Feature Request] Hook every key

### ISSUE THREAD

**Issue by shxdow** [mikeholler/pyty#2]
As far as I'm aware, F1-12 / CTRL / TAB / Windows / Block Maiusc ... don't produce any sound when pressed. Can they be added too?

**Comment by mikeholler** [comment]
Thanks for your comment and contributions lately! You bring up a good point, but I still think it should be limited to characters that are typed in documents. The reason for this is the sound that is being used is that of a letter arm hitting a page of paper in addition to the action of pressing down a letter key. The keys you're suggesting wouldn't actually "hit the page". I'm open to adding a sound for meta keys that don't actually modify what's on the page (e.g., SHIFT), but until we have a property licensed sound for that I am against adding all keys to the sound list.

If you want to add this functionality yourself, you can simply change:

```python
    else:
        sound = None
```

To:

```python
    else:
        sound = choice(k_generic)
```

In `pyty.py` in your own fork.
